"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import pymysql

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file explicitly with override to ensure it loads
env_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=env_path, override=True)

pymysql.install_as_MySQLdb()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# if not SECRET_KEY:
#     raise RuntimeError("DJANGO_SECRET_KEY is not set. Check backend/.env and load_dotenv().")

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", 'django-insecure-r4$x0ct&)wqn)yk*t23b3visyw%3jwtzcn4w#!50is5@a4)_fr')

# DEBUG = os.getenv("DEBUG") == "True"
DEBUG = os.getenv("DEBUG", "True") == "True"

# dev convenience (prevents DisallowedHost when you move between localhost/127.0.0.1)
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Razorpay - strip quotes if accidentally included
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "").strip("'\"")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "").strip("'\"")

# Debug: print to verify loading (remove in production)
# if DEBUG:
#     print(f"[settings] RAZORPAY_KEY_ID loaded: {bool(RAZORPAY_KEY_ID)}")
#     print(f"[settings] RAZORPAY_KEY_SECRET loaded: {bool(RAZORPAY_KEY_SECRET)}")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'corsheaders',
    
    'accounts',
    'locations',
    'branch_management',
    'subscriptions',
    'orders.apps.OrdersConfig',  # CHANGED: ensure OrdersConfig.ready() runs
    'payments.apps.PaymentsConfig',  # CHANGED: ensure PaymentsConfig.ready() runs
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES ={
    'default':{
        'ENGINE':'django.db.backends.mysql',  # This works for PyMySQL
        'NAME':'smart_laundry_db',
        'USER':'root',
        'PASSWORD':'Edwin@1520',
        'HOST':'localhost',
        'PORT':'3307',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("TIME_ZONE", "Asia/Kolkata")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# CORS / CSRF configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Allow cookies to be sent with cross-origin requests
CORS_ALLOW_CREDENTIALS = True

# IMPORTANT: For development, use Lax instead of None to avoid issues
# None requires HTTPS in modern browsers
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Dev over HTTP - keep False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Allow reading CSRF cookie in JS
CSRF_COOKIE_HTTPONLY = False

# IMPORTANT: Trust the frontend origin for CSRF
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# NEW: subscription monthly order generation horizon (used by jobs / subscribe hook)
MONTHLY_ORDER_GENERATE_DAYS_AHEAD = int(os.getenv("MONTHLY_ORDER_GENERATE_DAYS_AHEAD", "0"))

# NEW: on server start, catch up and ensure today's monthly orders exist (covers downtime at midnight)
ENABLE_MONTHLY_ORDER_STARTUP_CATCHUP = os.getenv("ENABLE_MONTHLY_ORDER_STARTUP_CATCHUP", "True") == "True"
MONTHLY_ORDER_STARTUP_CATCHUP_DAYS_AHEAD = int(os.getenv("MONTHLY_ORDER_STARTUP_CATCHUP_DAYS_AHEAD", "0"))

# NEW: toggle daily monthly-order generation thread (disable for multi-worker prod if needed)
ENABLE_DAILY_MONTHLY_ORDER_JOB = os.getenv("ENABLE_DAILY_MONTHLY_ORDER_JOB", "True") == "True"

# NEW: payment fine jobs
ENABLE_FINE_STARTUP_CATCHUP = os.getenv("ENABLE_FINE_STARTUP_CATCHUP", "True") == "True"
ENABLE_DAILY_FINE_JOB = os.getenv("ENABLE_DAILY_FINE_JOB", "True") == "True"

