# Generated by Django 6.0.1 on 2026-01-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicezone',
            name='pincode',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicezone',
            name='pincodes',
            field=models.JSONField(default='000000'),
            preserve_default=False,
        ),
    ]
